################################################################################
########## Data directory ##########



################################################################################
########## System ##########

# number of fermionic d.o.f (including spin)
NF = 28


